#!E:\EHPEA\Odoo10_virtual\Scripts\python.exe
import os
import sys
try:
    import wx
except:
    if os.name == 'posix':
        msg = '\n'.join([
            'Module "wx" not found.',
            'Install module "wx" by your OS utils.',
            'from terminal execute:',
            '\tsudo aptitude install python-wxgtk2.8',
            '',
            'if You don\'t have the aptitude application firstly execute:',
            '\t"sudo apt-get install aptitude"',
        ])
    elif os.name == 'nt':
        msg = '''Install wxpython from:

    http://sourceforge.net/projects/wxpython/files/wxPython/2.8.12.1/wxPython2.8-win32-unicode-2.8.12.1-py27.exe/download?use_mirror=netcologne

and rerun me.

If this won't help contact me:
    tymoteusz.jankowski@gmail.com
'''
    else:
        msg = '\n'.join([
            'Unsupported operating system (OS).',
            'Supported OS: Linux, Windows.',
        ])
    print msg
    sys.exit()

from windownow.windowNow import WindowNow

if __name__ == '__main__':
    app = wx.PySimpleApp(redirect=False)
    frame = WindowNow(None)
    app.MainLoop()
